# Наценка в процентах от базового курса
markup_percent: 0.9

# Список конкретных пар для экспорта
pairs:
  - from: usdttrc
    to:   cashrub
    amount:   10000000.00   # 10 000 000 RUB
    minamount: 100000.00     # от 100 000
    maxamount: 10000000.00   # до 10 000 000

  - from: cashrub
    to:   usdttrc
    amount:   362000.00     # 362 000 USDT
    minamount: 50000.00      # от 50 000
    maxamount: 30000000.00   # до 30 000 000

  - from: usdttrc
    to:   TCSBRUB
    amount:   5000000.00    # 5 000 000 RUB
    minamount: 5000.00       # от 5 000
    maxamount: 5000000.00    # до 5 000 000

  - from: usdttrc
    to:   SBERRUB
    amount:   5000000.00
    minamount: 5000.00
    maxamount: 5000000.00

  - from: usdttrc
    to:   sbprub
    amount:   5000000.00
    minamount: 5000.00
    maxamount: 5000000.00
